version: "3"
services:
  web: #service name
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests: #no need to add port as tests are going to run on container
    environment: #To make changes in environment
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
